const flowers = [{
    "id": 1,
    "name": "Tulip",
    "colors": "fuchsia",
    "unit_price": 942,
    "quantity": 544
  }, {
    "id": 2,
    "name": "Anemone",
    "colors": "green",
    "unit_price": 963,
    "quantity": 770
  }, {
    "id": 3,
    "name": "Magnolia",
    "colors": "magenta",
    "unit_price": 421,
    "quantity": 784
  }, {
    "id": 4,
    "name": "Sunflower",
    "colors": "gold",
    "unit_price": 978,
    "quantity": 36
  }, {
    "id": 5,
    "name": "Hibiscus",
    "colors": "cobalt",
    "unit_price": 611,
    "quantity": 24
  }, {
    "id": 6,
    "name": "Hibiscus",
    "colors": "turquoise",
    "unit_price": 576,
    "quantity": 481
  }, {
    "id": 7,
    "name": "Freesia",
    "colors": "coral",
    "unit_price": 363,
    "quantity": 530
  }, {
    "id": 8,
    "name": "Orchid",
    "colors": "lime",
    "unit_price": 865,
    "quantity": 657
  }, {
    "id": 9,
    "name": "Lily",
    "colors": "green",
    "unit_price": 863,
    "quantity": 701
  }, {
    "id": 10,
    "name": "Freesia",
    "colors": "maroon",
    "unit_price": 631,
    "quantity": 565
  }, {
    "id": 11,
    "name": "Peony",
    "colors": "cream",
    "unit_price": 740,
    "quantity": 273
  }, {
    "id": 12,
    "name": "Camellia",
    "colors": "turquoise",
    "unit_price": 523,
    "quantity": 761
  }, {
    "id": 13,
    "name": "Amaryllis",
    "colors": "burgundy",
    "unit_price": 507,
    "quantity": 41
  }, {
    "id": 14,
    "name": "Peony",
    "colors": "blue",
    "unit_price": 165,
    "quantity": 368
  }, {
    "id": 15,
    "name": "Marigold",
    "colors": "teal",
    "unit_price": 429,
    "quantity": 678
  }, {
    "id": 16,
    "name": "Jasmine",
    "colors": "ivory",
    "unit_price": 913,
    "quantity": 129
  }, {
    "id": 17,
    "name": "Peony",
    "colors": "cobalt",
    "unit_price": 802,
    "quantity": 272
  }, {
    "id": 18,
    "name": "Poppy",
    "colors": "purple",
    "unit_price": 484,
    "quantity": 639
  }, {
    "id": 19,
    "name": "Zinnia",
    "colors": "fuchsia",
    "unit_price": 746,
    "quantity": 312
  }, {
    "id": 20,
    "name": "Gardenia",
    "colors": "blue",
    "unit_price": 996,
    "quantity": 628
  }, {
    "id": 21,
    "name": "Amaryllis",
    "colors": "blue",
    "unit_price": 160,
    "quantity": 713
  }, {
    "id": 22,
    "name": "Lily",
    "colors": "beige",
    "unit_price": 530,
    "quantity": 366
  }, {
    "id": 23,
    "name": "Gardenia",
    "colors": "violet",
    "unit_price": 179,
    "quantity": 330
  }, {
    "id": 24,
    "name": "Lily",
    "colors": "fuchsia",
    "unit_price": 555,
    "quantity": 901
  }, {
    "id": 25,
    "name": "Tulip",
    "colors": "beige",
    "unit_price": 780,
    "quantity": 147
  }, {
    "id": 26,
    "name": "Camellia",
    "colors": "blue",
    "unit_price": 430,
    "quantity": 447
  }, {
    "id": 27,
    "name": "Hibiscus",
    "colors": "cream",
    "unit_price": 211,
    "quantity": 834
  }, {
    "id": 28,
    "name": "Daffodil",
    "colors": "blue",
    "unit_price": 903,
    "quantity": 884
  }, {
    "id": 29,
    "name": "Pansy",
    "colors": "red",
    "unit_price": 728,
    "quantity": 482
  }, {
    "id": 30,
    "name": "Violet",
    "colors": "peach",
    "unit_price": 903,
    "quantity": 747
  }]
  
  
  module.exports = flowers;